USE [master]
GO

/****** Object:  Database [rangphototstudio]    Script Date: 04/14/2019 21:12:32 ******/
CREATE DATABASE [rangphototstudio] ON  PRIMARY 
( NAME = N'rangphototstudio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\rangphototstudio.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'rangphototstudio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\rangphototstudio_log.LDF' , SIZE = 768KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [rangphototstudio] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rangphototstudio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [rangphototstudio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [rangphototstudio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [rangphototstudio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [rangphototstudio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [rangphototstudio] SET ARITHABORT OFF 
GO

ALTER DATABASE [rangphototstudio] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [rangphototstudio] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [rangphototstudio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [rangphototstudio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [rangphototstudio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [rangphototstudio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [rangphototstudio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [rangphototstudio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [rangphototstudio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [rangphototstudio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [rangphototstudio] SET  ENABLE_BROKER 
GO

ALTER DATABASE [rangphototstudio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [rangphototstudio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [rangphototstudio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [rangphototstudio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [rangphototstudio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [rangphototstudio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [rangphototstudio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [rangphototstudio] SET  READ_WRITE 
GO

ALTER DATABASE [rangphototstudio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [rangphototstudio] SET  MULTI_USER 
GO

ALTER DATABASE [rangphototstudio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [rangphototstudio] SET DB_CHAINING OFF 
GO

